---
- hosts: "{{ host }}"
  gather_facts: false
  vars:
  tasks:
    - ping:
    - name: Find Available Volume group
      command: whoami
      register: user
    - debug: 
        msg: "{{user.stdout}}"
    - name: Find Available Volume group
      command: /sbin/vgs --noheadings -o vg_name | tr -d "  "
      register: vg_name_output
    - debug: 
        msg: "{{vg_name_output.stdout}}"
    - set_fact:
        var_string_to_echo: "{{ vg_name_output.stdout }}"
    - name: Find availabe size in vg
      command: vgs --noheadings -o pv_free | tr -d '  ' | sed 's/\.00m*//g'
      register: vg_size_output
    - debug: 
        msg: "{{vg_size_output.stdout}}"
    - set_fact:
        var_string_to_echo: "{{ vg_size_output.stdout }}"
    - debug: var=var_string_to_echo
      run_once: true
