---
- hosts: all
  gather_facts: false
  tasks:
    - ping:
    - name: Create variable from command
      command: "echo Hello"
      register: command_output
    - debug: 
        msg: "{{command_output.stdout}}"
    - set_fact:
        var_string_to_echo: "{{ var_command_output.stdout }}"
