---
- hosts: all
  gather_facts: false
  vars:
    var_cmd: "{{ cmd }}"
  tasks:
    - ping:
    - name: Create variable from command
      command: "{{ var_cmd }}"
      register: command_output
    - debug: 
        msg: "{{command_output.stdout}}"
    - set_fact:
        var_string_to_echo: "{{ command_output.stdout }}"
